import 'package:flutter/material.dart';

// Colori 
const kBackgroundColor = Color(0xFFFEFEFE);
const kTitleTextColor = Color(0xFF303030);
const kBodyTextColor = Color(0xFF4B4B4B);
const kTextLightColor = Color(0xFF959595);
const infetticolore = Color(0xFFFF8748);
const morticolore = Color(0xFFFF4848);
const ricoveraticolore = Color(0xFF36C12C);
const kPrimaryColor = Color(0xFF3382CC);
final kShadowColor = Color(0xFFB7B7B7).withOpacity(.16);
final kActiveShadowColor = Color(0xFF4056C6).withOpacity(.15);

//stile testo
const kHeadingTextStyle = TextStyle(
  fontSize: 22,
  fontWeight: FontWeight.w600,
);

const kSubTextStyle = TextStyle(fontSize: 16, color: kTextLightColor);

const kTitleTextstyle = TextStyle(
  fontSize: 18,
  color: kTitleTextColor,
  fontWeight: FontWeight.bold,
);

//DATI PER IL PICKER
const PickerData = '''
[
    [
"Afghanistan-AFG",
"Albania-ALB",
"Algeria-DZA",
"American Samoa-ASM",
"Angola-AGO",
"Anguilla-AIA",
"Antigua and Barbuda-ATG",
"Argentina-ARG",
 "Armenia-ARM",
 "Aruba-ABW",
 "Australia-AUS",
 "Austria-AUT",
 "Azerbaijan-AZE",
 "Bahamas-BHS",
 "Bahrain-BHR",
 "Bangladesh-BGD",
 "Barbados-BRB",
 "Belarus-BLR",
 "Belgium-BEL",
 "Belize-BLZ",
 "Benin-BEN",
 "Bermuda-BMU",
 "Bhutan-BTN",
 "Bolivia, Plurinational State of-BOL",
 "Bolivia-BOL",
 "Bosnia-BIH",
 "Botswana-BWA",
 "Bouvet Island-BVT",
 "Brazil-BRA",
 "British Indian Ocean Territory-IOT",
 "Brunei-BRN",
 "Bulgaria-BGR",
 "Burkina Faso-BFA",
 "Burundi-BDI",
 "Cabo Verde-CPV",
 "Cambodia-KHM",
 "Cameroon-CMR",
 "Canada-CAN",
 "Cayman Islands-CYM",
 "Central African Republic-CAF", 
 "Caribbean Netherlands-BES", 
 "Chad-TCD",
 "Chile-CHL",
 "China-CHN",
 "Christmas Island-CXR",
 "Cocos (Keeling) Islands-CCK",
 "Colombia-COL",
 "Comoros-COM",
 "Congo-COG",
 "Congo, the Democratic Republic of the-COD",
 "Cook Islands-COK",
 "Costa Rica-CRI",
 "Côte d'Ivoire-CIV",
 "Croatia-HRV",
 "Cuba-CUB", 
 "Curacao-CUW",
 "Cyprus-CYP",
 "Czechia-CZE", 
 "Denmark-DNK",
 "Djibouti-DJI",
 "Dominica-DMA",
 "Dominican Republic-DOM",
 "Ecuador-ECU",
 "Egypt-EGY",
 "El Salvador-SLV",
 "Equatorial Guinea-GNQ",
 "Eritrea-ERI",
 "Estonia-EST",
 "Ethiopia-ETH",
 "Ethiopia-ETH",
 "Falkland Islands (Malvinas)-FLK", 
 "Faroe Islands-FRO",
 "Fiji-FJI",
 "Finland-FIN",
 "France-FRA",
 "French Guiana-GUF",
 "French Polynesia-PYF",
 "French Southern Territories-ATF",
 "Gabon-GAB",
 "Gambia-GMB",
 "Georgia-GEO",
 "Germany-DEU",
 "Ghana-GHA",
 "Gibraltar-GIB",
 "Greece-GRC",
 "Greenland-GRL",
 "Grenada-GRD",
 "Guadeloupe-GLP",
 "Guam-GUM", 
 "Guatemala-GTM", 
 "Guernsey-GGY", 
 "Guinea-GIN",
 "Guinea-Bissau-GNB",
 "Guyana-GUY",
 "Haiti-HTI", 
 "Heard Island and McDonald Islands-HMD",  
 "Holy See (Vatican City State)-VAT",
 "Honduras-HND",
 "Hong Kong-HKG", 
 "Hungary-HUN",
 "Iceland-ISL",
 "India-IND",
 "Indonesia-IDN",
 "Iran-IRN",  
 "Iraq-IRQ",
 "Ireland-IRL",
 "Isle of Man-IMN",
 "Israel-ISR", 
 "Italy-ITA", 
 "Jamaica-JAM",
 "Japan-JPN", 
 "Jersey-JEY",
 "Channel Islands-JEY", 
 "Jordan-JOR",
 "Kazakhstan-KAZ",
 "Kenya-KEN",
 "Kiribati-KIR",
 "Kosovo-RKS", 
 "N. Korea-PRK",
 "S. Korea-KOR",
 "Kuwait-KWT", 
 "Kyrgyzstan-KGZ",
 "Lao People s Democratic Republic-LAO", 
 "Latvia-LVA",
 "Lebanon-LBN",
 "Lesotho-LSO", 
 "Liberia-LBR",
 "Libyan Arab Jamahiriya-LBY",
 "Liechtenstein-LIE", 
 "Lithuania-LTU",
 "Luxembourg-LUX",  
 "Macao-MAC", 
 "Macedonia-MKD",
 "Madagascar-MDG",
 "Malawi-MWI",
 "Malaysia-MYS",
 "Maldives-MDV",
 "Mali-MLI",
 "Malta-MLT", 
 "Marshall Islands-MHL",
 "Martinique-MTQ", 
 "Mauritania-MRT",
 "Mauritius-MUS", 
 "Mayotte-MYT", 
 "Mexico-MEX",
 "Micronesia Federated States of-FSM",  
 "Moldova Republic of-MDA",
 "Monaco-MCO", 
 "Mongolia-MNG",
 "Montenegro-MNE",
 "Montserrat-MSR",
 "Morocco-MAR",
 "Mozambique-MOZ", 
 "Myanmar-MMR",
 "Burma-MMR",
 "Namibia-NAM",
 "Nauru-NRU", 
 "Nepal-NPL",
 "Netherlands-NLD", 
 "Netherlands Antilles-ANT",
 "New Caledonia-NCL",  
 "New Zealand-NZL",
 "Nicaragua-NIC",
 "Niger-NER",
 "Nigeria-NGA",
 "Niue-NIU",
 "Norfolk Island-NFK", 
 "Northern Mariana Islands-MNP",  
 "Norway-NOR",
 "Oman-OMN",
 "Pakistan-PAK",
 "Palau-PLW", 
 "Palestinian Territory, Occupied-PSE",
 "Panama-PAN",
 "Papua New Guinea-PNG",
 "Paraguay-PRY",
 "Peru-PER",
 "Philippines-PHL",
 "Pitcairn-PCN",
 "Poland-POL",
 "Portugal-PRT", 
 "Puerto Rico-PRI",
 "Qatar-QAT",
 "Réunion-REU",  
 "Romania-ROU",
 "Russia-RUS", 
 "Rwanda-RWA",
 "St. Barth-BLM",
 "Saint Helena Ascension and Tristan da Cunha-SHN",
 "Saint Kitts and Nevis-KNA",
 "Saint Lucia-LCA",
 "Saint Pierre and Miquelon-SPM",
 "Saint Martin-MAF",
 "Sint Maarten-SXM", 
 "Saint Vincent and the Grenadines-VCT",
 "Samoa-WSM",
 "San Marino-SMR", 
 "Sao Tome and Principe-STP",
 "Saudi Arabia-SAU",
 "Senegal-SEN",
 "Serbia-SRB",
 "Seychelles-SYC", 
 "Sierra Leone-SLE", 
 "Singapore-SGP", 
 "Slovakia-SVK", 
 "Slovenia-SVN",
 "Solomon Islands-SLB",
 "Somalia-SOM",
 "South Africa-ZAF",
 "South Georgia and the South Sandwich Islands-SGS",  
 "Spain-ESP",
 "Sri Lanka-LKA",
 "Sudan-SDN",
 "Suriname-SUR",
 "Svalbard and Jan Mayen-SJM",
 "Swaziland-SWZ", 
 "Sweden-SWE",
 "Switzerland-CHE",
 "Syrian Arab Republic-SYR", 
 "Taiwan Province of China-TWN",
 "Taiwan-TWN",
 "Tajikistan-TJK",
 "Tanzania United Republic of-TZA",
 "Thailand-THA",
 "Timor-Leste-TLS", 
 "Togo-TGO",
 "Tokelau-TKL",
 "Tonga-TON",
 "Trinidad and Tobago-TTO",
 "Tunisia-TUN",
 "Turkey-TUR",
 "Turkmenistan-TKM",
 "Turks and Caicos Islands-TCA", 
 "Tuvalu-TUV",
 "Uganda-UGA",
 "Ukraine-UKR",
 "UAE-ARE", 
 "UK-GBR",
 "USA-USA",
 "United States Minor Outlying Islands-UMI",
 "Uruguay-URY",
 "Uzbekistan-UZB",
 "Vanuatu-VUT",
 "Venezuela-VEN",
 "Vietnam-VNM", 
 "British Virgin Islands-VGB",
 "U.S. Virgin Islands-VIR",
 "Wallis and Futuna-WLF",
 "Western Sahara-ESH", 
 "Yemen-YEM",
 "Zambia-ZMB",
 "Zimbabwe-ZWE"
    ]
    
]
    ''';